#ifndef DYNAMIC_H_INCLUDED
#define DYNAMIC_H_INCLUDED

#define DYNAMIC_VERSION "0.1.0"
#define DYNAMIC_VERSION_MAJOR 0
#define DYNAMIC_VERSION_MINOR 1
#define DYNAMIC_VERSION_PATCH 0

#include <dynamic/vector.h>

#endif /* DYNAMIC_H_INCLUDED */
